inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - feature
    - it
    - namespace

Metrics/MethodLength:
  Max: 15
  ExcludedMethods:
    - change

Metrics/AbcSize:
  Max: 17
  Exclude:
    - db/migrate/*
