version: '3.7'
services:
  bot:
    build: .
    depends_on:
      - db
    volumes:
      - .:/memach/
    stdin_open: true
    tty: true
  db:
    image: postgres:12.1-alpine
    volumes:
      - ./db/data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
