default: &default
  adapter: <%= ENV.fetch('DB_ADAPTER') { 'postgres' } %>
  encoding: unicode
  pool: <%= ENV.fetch('DB_MAX_THREADS') { 5 } %>
  host: <%= ENV.fetch('DB_HOST') { 'db' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { 'postgres' } %>
  username: <%= ENV.fetch('DB_USER') { 'postgres' } %>

development:
  <<: *default
  database: memach_development

test:
  <<: *default
  database: memach_test

production:
  url: <%= ENV['DATABASE_URL'] %>
