default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  username: <%= ENV['DB_USER'] %>

development:
  <<: *default
  database: memach_development

test:
  <<: *default
  database: memach_test

production:
  url: <%= ENV['DATABASE_URL'] %>
